anykernel_boeffla: sync with anykernel2 repo
Signed-off-by: sunilpaulmathew <sunil.kde@gmail.com>

diff --git a/anykernel_boeffla/META-INF/com/google/android/update-binary b/anykernel_boeffla/META-INF/com/google/android/update-binary
--- a/anykernel_boeffla/META-INF/com/google/android/update-binary
+++ b/anykernel_boeffla/META-INF/com/google/android/update-binary
@@ -4,89 +4,81 @@
 #
 # Original and credits: osm0sis @ xda-developers
 #
-# Modified by Lord Boeffla & sunilpaulmathew @ xda-developers.com
+# Modified by sunilpaulmathew @ xda-developers.com
 
 OUTFD=/proc/self/fd/$2;
-ZIP="$3";
-DIR=`dirname "$ZIP"`;
+ZIPFILE="$3";
+DIR=`dirname "$ZIPFILE"`;
 
-
-## internal functions
-
-ui_print() 
-{
-	until [ ! "$1" ]; do
-		echo -e "ui_print $1\nui_print" > $OUTFD;
-		shift;
-	done;
+ui_print() {
+  until [ ! "$1" ]; do
+    echo -e "ui_print $1\nui_print" > $OUTFD;
+    shift;
+  done;
 }
-
-show_progress() 
-{
-	echo "progress $1 $2" > $OUTFD;
+show_progress() { echo "progress $1 $2" > $OUTFD; }
+file_getprop() { grep "^$2=" "$1" | cut -d= -f2; }
+if [ ! "$(getprop 2>/dev/null)" ]; then
+  getprop() {
+    local propval="$(file_getprop /default.prop $1 2>/dev/null)";
+    test "$propval" || local propval="$(file_getprop /system/build.prop $1 2>/dev/null)";
+    test "$propval" && echo "$propval" || echo "";
+  }
+fi;
+cleanup() { rm -rf /tmp/anykernel; }
+debugging() {
+  case $(basename "$ZIPFILE" .zip) in
+    *-debugging)
+      ui_print " ";
+      ui_print "Creating debugging archive in zip directory...";
+      $bb tar -czvf "$DIR/anykernel2-$(date +%Y-%m-%d_%H%M%S)-debug.tgz" /tmp/*;
+    ;;
+  esac;
 }
-
-set_perm_recursive() 
-{
-	dirs=$(echo $* | $bb awk '{ print substr($0, index($0,$5)) }');
-	
-	for i in $dirs; do
-		chown -R $1.$2 $i; chown -R $1:$2 $i;
-		find "$i" -type d -exec chmod $3 {} +;
-		find "$i" -type f -exec chmod $4 {} +;
-	done;
+abort() {
+  ui_print "$*";
+  debugging;
+  if [ ! -f /tmp/anykernel/anykernel.sh -o "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanuponabort 2>/dev/null)" == 1 ]; then
+    cleanup;
+  fi;
+  umount /system;
+  umount /vendor 2>/dev/null;
+  umount /data 2>/dev/null;
+  exit 1;
 }
-
-file_getprop() 
-{ 
-	grep "^$2" "$1" | cut -d= -f2;
-}
-
-getprop()
-{ 
-	test -e /sbin/getprop && /sbin/getprop $1 || file_getprop /default.prop $1;
-}
-
-abort()
-{ 
-	ui_print " ";
-	ui_print "$*";
-	umount /system;
-	umount /data;
-	exit 1;
-}
-
-
-## start of main script
 
 show_progress 1.34 4;
 ui_print " ";
-
+cleanup;
 mkdir -p /tmp/anykernel/bin;
 cd /tmp/anykernel;
-unzip -o "$ZIP";
-
+unzip -o "$ZIPFILE";
 if [ $? != 0 -o -z "$(ls /tmp/anykernel/tools)" ]; then
-	abort "Error - unzip failed. Aborting.";
+  abort "Unzip failed. Aborting...";
 fi;
-
-chmod -R 755 /tmp/anykernel/tools /tmp/anykernel/bin;
 bb=/tmp/anykernel/tools/busybox;
+chmod 755 $bb;
+$bb chmod -R 755 /tmp/anykernel/tools /tmp/anykernel/bin;
+
+if [ -f /tmp/anykernel/banner ]; then
+  while IFS='' read -r line || $bb [[ -n "$line" ]]; do
+    ui_print "$line";
+  done < /tmp/anykernel/banner;
+  ui_print " ";
+  ui_print " ";
+fi;
 
 ui_print "Boeffla-Kernel-kltexxx-unofficial";
 ui_print " ";
 ui_print "(c) sunilpaulmathew@xda-developers.com";
 ui_print " ";
 
-umount /system;
+umount /system 2>/dev/null;
+umount /vendor 2>/dev/null;
 mount -o ro -t auto /system;
-mount /data;
+mount -o ro -t auto /vendor 2>/dev/null;
+mount /data 2>/dev/null;
 test -f /system/system/build.prop && root=/system;
-
-# remove kernel survival script as it is useless with anykernel
-mount -o remount,rw -t auto /system;
-rm $root/system/addon.d/97-boeffla-kernel.sh
-mount -o remount,ro -t auto /system;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.devicecheck)" == 1 ]; then
 	ui_print "* Checking device compatibility...";
@@ -128,38 +120,50 @@ ui_print "* Installing kernel...";
 ui_print " ";
 
 for i in $($bb --list); do
-	$bb ln -s $bb /tmp/anykernel/bin/$i;
+  $bb ln -s $bb /tmp/anykernel/bin/$i;
 done;
-
 if [ $? != 0 -o -z "$(ls /tmp/anykernel/bin)" ]; then
-	abort "Recovery busybox setup failed. Aborting.";
+  abort "Recovery busybox setup failed. Aborting...";
 fi;
-
 PATH="/tmp/anykernel/bin:$PATH" $bb ash /tmp/anykernel/anykernel.sh $2;
-
 if [ $? != "0" ]; then
-	abort;
+  abort;
 fi;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.modules)" == 1 ]; then
-	ui_print "* Copying modules...";
-	ui_print " ";
-
-	mount -o remount,rw -t auto /system;
-	if [ ! -d $root/system/lib/modules ]; then
-	    mkdir -p $root/system/lib/modules;
-	fi;
-	rm -rf $root/system/lib/modules/*;
-	cp -rf /tmp/anykernel/modules/* $root/system/lib/modules/;
-	set_perm_recursive 0 0 0755 0644 $root/system/lib/modules;
-	mount -o remount,ro -t auto /system;
+  ui_print " ";
+  ui_print "Pushing modules...";
+  mount -o rw,remount -t auto /system;
+  mount -o rw,remount -t auto /vendor 2>/dev/null;
+  cd /tmp/anykernel/modules;
+  for module in $(find . -name '*.ko'); do
+    if [ ! -e /$module ]; then
+      case $module in
+        */vendor/*) mod=vendor;;
+        *) mod=system;;
+      esac;
+    fi;
+    $bb cp -rLf $module /$module;
+    $bb chown 0:0 /$module;
+    $bb chmod 644 /$module;
+    if [ "$mod" ]; then
+      chcon "u:object_r:${mod}_file:s0" /$module;
+    fi;
+  done;
+  cd /tmp/anykernel;
+  mount -o ro,remount -t auto /system;
+  mount -o ro,remount -t auto /vendor 2>/dev/null;
 fi;
 
+debugging;
+
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanup)" == 1 ]; then
-	rm -rf /tmp/anykernel;
+  cleanup;
 fi;
 
 umount /system;
-umount /data;
-ui_print "* Finished, please reboot.";
+umount /vendor 2>/dev/null;
+umount /data 2>/dev/null;
 ui_print " ";
+ui_print " ";
+ui_print "Done!";
