Incorporating recent patches from osm0sis's AnyKernel2 repo [Last commit: AK2: add AOSP boot_img_hdr_v1 support] @e1ae4412f5c748fd9e94a58fcfe50a5348774d1a
Signed-off-by: osm0sis <osm0sis@outlook.com>
Signed-off-by: sunilpaulmathew <sunil.kde@gmail.com>

diff --git a/anykernel_boeffla/META-INF/com/google/android/update-binary b/anykernel_boeffla/META-INF/com/google/android/update-binary
--- a/anykernel_boeffla/META-INF/com/google/android/update-binary
+++ b/anykernel_boeffla/META-INF/com/google/android/update-binary
@@ -1,6 +1,6 @@
 #!/sbin/sh
 
-# AnyKernel2 Backend Script
+# AnyKernel2 Backend
 #
 # Original and credits: osm0sis @ xda-developers
 #
@@ -35,15 +35,22 @@ debugging() {
     ;;
   esac;
 }
+unmount_all() {
+  (umount /system;
+  if [ -d /system_root -a ! -f /system/build.prop ]; then
+    umount /system_root;
+  fi;
+  umount /system;
+  umount /vendor;
+  umount /data) 2>/dev/null;
+}
 abort() {
   ui_print "$*";
   debugging;
   if [ ! -f /tmp/anykernel/anykernel.sh -o "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanuponabort 2>/dev/null)" == 1 ]; then
     cleanup;
   fi;
-  umount /system;
-  umount /vendor 2>/dev/null;
-  umount /data 2>/dev/null;
+  unmount_all;
   exit 1;
 }
 
@@ -69,56 +76,71 @@ if [ -f /tmp/anykernel/banner ]; then
 fi;
 
 ui_print "Boeffla-Kernel (unofficial) for Samsung Galaxy S5";
+if [ -f /tmp/anykernel/version ]; then
+  ui_print " ";
+  while IFS='' read -r line || $bb [[ -n "$line" ]]; do
+    ui_print "$line";
+  done < /tmp/anykernel/version;
+  ui_print " ";
+fi;
 ui_print " ";
 ui_print "...(c) sunilpaulmathew@xda-developers.com...";
 ui_print " ";
+ui_print " ";
 
-umount /system 2>/dev/null;
-umount /vendor 2>/dev/null;
+unmount_all;
 mount -o ro -t auto /system;
 mount -o ro -t auto /vendor 2>/dev/null;
 mount /data 2>/dev/null;
 test -f /system/system/build.prop && root=/system;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.devicecheck)" == 1 ]; then
-	ui_print "* Checking device compatibility...";
-	ui_print "  - Detected product.device: $(getprop ro.product.device)";
-	ui_print "  - Detected build.product : $(getprop ro.build.product)";
-	ui_print "  - Detected display.series: $(getprop ro.display.series)";
-
-	for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
-		testname="$(file_getprop /tmp/anykernel/anykernel.sh device.name$i)";
-		if [ "$(getprop ro.product.device)" == "$testname" -o \
-			"$(getprop ro.build.product)" == "$testname" -o \
-			"$(getprop ro.display.series)" == "$testname" ]; then
-			match=1;
-		fi;
-	done;
-
-	if [ "$match" != 1 ]; then
-		abort "This kernel is NOT compatible with your device. Aborting.";
-	else
-		ui_print "  Kernel is compatible.";
-	fi;
-
-	ui_print " ";
+  ui_print "Checking device...";
+  device="$(getprop ro.product.device)";
+  product="$(getprop ro.build.product)";
+  for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
+    testname="$(file_getprop /tmp/anykernel/anykernel.sh device.name$i)";
+    test "$testname" || break;
+    if [ "$device" == "$testname" -o "$product" == "$testname" ]; then
+      ui_print "$testname";
+      match=1;
+      break;
+    fi;
+  done;
+  ui_print " ";
+  if [ "$match" != 1 ]; then
+    abort "This kernel is NOT compatible with your device. Aborting.";
+  else
+    ui_print "  Kernel is compatible.";
+  fi;
+  ui_print " ";
 fi;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.initd)" == 1 ]; then
-	ui_print "* Creating init.d...";
-	ui_print " ";
-
-	mount -o remount,rw -t auto /system;
-	if [ ! -d $root/system/etc/init.d ]; then
-	    mkdir $root/system/etc/init.d;
-	fi;
-	set_perm_recursive 0 0 0755 0755 $root/system/etc/init.d;
-	mount -o remount,ro -t auto /system;
+  ui_print "* Creating init.d...";
+  ui_print " ";
+  mount -o remount,rw -t auto /system;
+  if [ ! -d $root/system/etc/init.d ]; then
+    mkdir $root/system/etc/init.d;
+  fi;
+  set_perm_recursive 0 0 0755 0755 $root/system/etc/init.d;
+  mount -o remount,ro -t auto /system;
 fi;
 
-ui_print "* Installing kernel...";
-ui_print " ";
+if [ -f /system/system/build.prop ]; then
+  umount /system;
+  umount /system 2>/dev/null;
+  mkdir /system_root 2>/dev/null;
+  mount -o ro -t auto /dev/block/bootdevice/by-name/system /system_root;
+  mount -o bind /system_root/system /system;
+  unset root;
+fi;
+savedpath="$LD_LIBRARY_PATH";
+savedpre="$LD_PRELOAD";
+unset LD_LIBRARY_PATH;
+unset LD_PRELOAD;
 
+ui_print "Installing...";
 for i in $($bb --list); do
   $bb ln -s $bb /tmp/anykernel/bin/$i;
 done;
@@ -137,22 +159,18 @@ if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.modules)" == 1 ]; then
   mount -o rw,remount -t auto /vendor 2>/dev/null;
   cd /tmp/anykernel/modules;
   for module in $(find . -name '*.ko'); do
-    case $module in
-      */system/*) modtarget=$root/$module;;
-      *) modtarget=/$module;;
-    esac;
-    if [ ! -e $modtarget ]; then
+    if [ ! -e /$module ]; then
       case $module in
         */vendor/*) mod=vendor;;
         *) mod=system;;
       esac;
     fi;
-    mkdir -p $(dirname $modtarget);
-    $bb cp -rLf $module $modtarget;
-    $bb chown 0:0 $modtarget;
-    $bb chmod 644 $modtarget;
+    mkdir -p $(dirname /$module);
+    $bb cp -rLf $module /$module;
+    $bb chown 0:0 /$module;
+    $bb chmod 644 /$module;
     if [ "$mod" ]; then
-      chcon "u:object_r:${mod}_file:s0" $modtarget;
+      chcon "u:object_r:${mod}_file:s0" /$module;
     fi;
   done;
   cd /tmp/anykernel;
@@ -166,9 +184,11 @@ if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanup)" == 1 ]; then
   cleanup;
 fi;
 
-umount /system;
-umount /vendor 2>/dev/null;
-umount /data 2>/dev/null;
+test "$savedpath" && export LD_LIBRARY_PATH="$savedpath";
+test "$savedpre" && export LD_PRELOAD="$savedpre";
+
+unmount_all;
+
 ui_print " ";
 ui_print " ";
 ui_print "Done!";
